# Activity One

The skeleton code below is created so that you can have a go at writing your own implementation of collaborative filtering.

Collaborative filtering is a popular technique used in recommendation systems to personalise and improve user experiences. The concept behind collaborative filtering is to analyse the behaviour and preferences of a group of users to recommend items or content to another user based on their similarities with the group. This technique can be applied to various types of data, such as movies, music, books, and products. Collaborative filtering works by building a model that identifies patterns and similarities in user behaviour and then uses these patterns to predict what items a user is likely to enjoy. By leveraging the collective intelligence of a group, collaborative filtering algorithms can generate highly accurate recommendations, making it a powerful tool for e-commerce, content-based websites, and other recommendation-based systems. In this way, collaborative filtering enables businesses to offer personalised experiences to their users, which can lead to increased engagement, loyalty, and revenue.

The pseudocode is explained as:

1. Collect data on user preferences for a set of items.
2. Represent the user preferences as a matrix, with each row representing a user and each column representing an item.
3. Compute the similarity between each pair of users using a similarity metric, such as cosine similarity or Pearson correlation.
4. For a target user, identify the top N most similar users based on the similarity metric.
5. For each item the target user has not rated, predict the rating by computing the weighted average of the ratings given by the most similar users, where the weights are the similarities between the users and the target user.
6. Recommend the top N items with the highest predicted ratings.

HAVE A GO! 

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


def similarity(user1, user2):
    # Calculate the dot product of the two user vectors
    dot_product = np.dot(user1, user2)
    # Calculate the magnitude of the two user vectors
    magnitude = np.sqrt(np.sum(user1 ** 2) * np.sum(user2 ** 2))
    # Calculate the similarity between the two users
    similarity = 
    return similarity

In [10]:
def predict_rating(user_ratings, movie_ratings):
    # Find the indices of the users who rated the movie
    rated_indices = np.where(movie_ratings != 0)[0]
    # Get the ratings of the movie by the rated users
    ratings = 
    # Get the user vectors of the rated users
    rated_users = user_ratings[]
    # Calculate the similarities between the rated users and the target user
    similarities = [similarity(user_ratings[0], rated_users[i]) for i in range(len(rated_indices))]
    # Calculate the weighted average of the ratings, using the similarities as weights
    weighted_sum = np.dot(similarities, ratings)
    weighted_sum /= np.sum(similarities)
    return weighted_sum

In [11]:
def recommend_movies(user_ratings):
    # Get the number of users and movies
    num_users, num_movies = 
    # Choose a target user to make recommendations for
    target_user = 0
    # Find the indices of the unwatched movies by the target user
    unwatched_indices = np.where(user_ratings[target_user] == 0)[0]
    # Predict the ratings for the unwatched movies
    predicted_ratings = [predict_rating(user_ratings, user_ratings[:, movie_index]) for movie_index in unwatched_indices]
    # Sort the movies by the predicted rating in descending order
    sorted_indices = np.argsort(predicted_ratings)[::-1]
    # Get the top 3 recommended movies
    top_movies = 
    recommended_movies = [f"Movie {i+1}" for i in top_movies]
    return recommended_movies

# Create a sample ratings matrix
ratings = np.array([[3, 0, 0, 5], [0, 4, 0, 3], [1, 0, 2, 4], [5, 0, 3, 0], [0, 2, 4, 0]])

# Make movie recommendations for the target user
recommended_movies = recommend_movies()

# Print the recommended movies
print("Recommended movies:", recommended_movies)

Recommended movies: ['Movie 1', 'Movie 2']


# Activity 2

Now we will look at completing a few exercises related to recommendation systems from your textbook.

**Exercise 9.2.1:** Three computers, A, B, and C, have the numerical features
listed below:

            Feature      A       B      C
    Processor Speed   3.06    2.68   2.92
    Disk Size          500     320    640
    Main-Memory Size     6       4      6
    
We may imagine these values as defining a vector for each computer; for instance, A’s vector is [3.06, 500, 6]. We can compute the cosine distance between any two of the vectors, but if we do not scale the components, then the disk size will dominate and make differences in the other components essentially invisible. Let us use 1 as the scale factor for processor speed, α for the disk size, and β for the main memory size.

(a) In terms of α and β, compute the cosines of the angles between the vectors
for each pair of the three computers.


**Exercise 9.2.3:** A certain user has rated the three computers of Exercise 9.2.1 as follows: 
    A: 4 stars
    B: 2 stars
    C: 5 stars.
    
(a) Normalize the ratings for this user.

(b) Compute a user profile for the user, with components for processor speed,
disk size, and main memory size, based on the data of Exercise 9.2.1.

        a    b    c    d    e    f    g    h
    A   4    5         5    1         3    2
    B        3    4    3    1    2    1
    C   2         1    3         4    5    3

    Figure 9.8: A utility matrix for exercises
    
    
Exercise 9.3.1 : Figure 9.8 is a utility matrix, representing the ratings, on a 1–5 star scale, of eight items, a through h, by three users A, B, and C. Compute the following from the data of this matrix.

(a) Treating the utility matrix as boolean, compute the Jaccard distance between each pair of users.

(b) Repeat Part (a), but use the cosine distance.

# Activity 3: UV Decomposition

UV decomposition, also known as matrix factorization, is a technique used in collaborative filtering algorithms to predict user preferences. The technique involves breaking down a large user-item preference matrix into two smaller matrices: a user matrix and an item matrix.

In UV decomposition, each row of the user matrix represents a user, and each column of the item matrix represents an item. The values in the matrices represent the degree to which each user likes each item.

The goal of UV decomposition is to factorize the original preference matrix into two smaller matrices such that the product of the matrices approximates the original matrix. This can be achieved using various optimization techniques, such as gradient descent.

The resulting user and item matrices can then be used to predict user preferences for new items. When a user expresses preferences for a set of items, the algorithm can compute a weighted average of the item vectors for those items, using the weights as the user's preferences.

UV decomposition has become a popular approach for recommendation systems because it can handle large sparse matrices and can be used to make accurate predictions even when a user has rated only a small fraction of the items.

The pseudocode for this method is as such:

Input:

    - A user-item preference matrix M with n rows (users) and m columns (items)
    
    - The number of latent factors k to use for the decomposition

Output:

- Two matrices U and V that together approximate the original matrix M

   1. Initialize U and V to random values between 0 and 1

   2. Repeat until convergence:
   
       a. Update U by minimizing the objective function:
          
          ||M - UV^T||^2 + lambda*(||U||^2 + ||V||^2)  using an optimization algorithm such as gradient descent
          
          
       b. Update V by minimizing the same objective function, using U^T instead of U

   3. Return the final U and V matrices

   4. To make recommendations for a user u:
       a. Compute the dot product of u's row in U and all columns in V
       b. Sort the resulting scores in descending order
       c. Recommend the top items to the user
       
Note that in step 2, lambda is a regularization parameter that helps prevent overfitting. It can be set using cross-validation or other techniques. Also, the optimization algorithm used to update U and V can vary depending on the specific application, with methods like stochastic gradient descent and alternating least squares being common choices.

In [16]:
import numpy as np

def uv_decomposition(R, k, learning_rate, regularization):
    """
    Performs UV decomposition on the input matrix R, with a target rank of k, using stochastic gradient descent (SGD).
    Returns the decomposed matrices U and V.
    """
    # Initialize U and V with random values
    num_users, num_items = R.shape
    U = #num users by k
    V = #k by num items

    # Perform stochastic gradient descent to optimize U and V
    for epoch in range(10):
        for i in range(#users):
            for j in range(#items):
                if R[i, j] > 0:
                    error = R[i, j] - np.dot(U[i, :], V[:, j])
                    U[i, :] += learning_rate * (error * V[:, j] - regularization * U[i, :])
                    V[:, j] += learning_rate * (error * U[i, :] - regularization * V[:, j])

    # Return the decomposed matrices U and V
    return U, V


In [31]:
# Create a sample matrix R
R = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4]
])

# Perform UV decomposition on R
U, V = uv_decomposition(R, k=3, learning_rate=0.1, regularization=0.1)

# Reconstruct the matrix R using the decomposed matrices U and V
R_reconstructed = #get the dot product 

# Print the original matrix R and the reconstructed matrix R
print("Original R:")
print(R)
print("Reconstructed R:")
print(R_reconstructed)


Original R:
[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]
Reconstructed R:
[[4.78189885 2.76868319 2.90291074 0.99591564]
 [3.76944354 2.21151163 2.49243155 1.00317761]
 [1.05026055 0.86071774 5.54756854 4.88243146]
 [0.98465631 0.67373038 4.5952831  3.86867847]
 [1.71396237 1.09959075 4.91030523 3.91255557]]


# Activity 4: Questions on Recommendation Systems

Have a go at answering some of these questions from Big Data Fundamentals



Big Data Fundamentals: Movie and music recommendations
Quiz 16: Collaborative filtering

    Instructions for Questions 5 and 6
    Consider the following rating matrix:

        A	B	C	D	E
    U1	1	0	1	0	1
    U2	1	1	1	1	1
    U3	1	0	0	0	1

Calculate the Jaccard similarity between each of the users. 

Instructions for Questions 7 and 8
Consider the following rating matrix:

        A	B	C	D	E
    U1	1	1	1	0	1
    U2	1	0	1	1	0
    U3	1	0	1	0	1
Calculate the Jaccard similarity between each of the users. 